CREATE TABLE departments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    location    VARCHAR(255),
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    patronymic    VARCHAR(255),
    last_name     VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255),
    phone         VARCHAR(255),
    job_title     VARCHAR(255)                            NOT NULL,
    department_id BIGINT,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT FK_EMPLOYEES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id)
);